version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
    - ./docs/.vuepress/dist:/usr/share/nginx/html
    ports:
    - "8181:80"
    environment:
    - NGINX_HOST=docs.zoerkler.me
    - NGINX_PORT=80
    labels:
    - traefik.enable=true
    - traefik.http.routers.raspi-doku.rule=Host(`docs.zoerkler.me`)
    networks: 
      - web
networks:
  web:
    external: true
